/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.DAOCliente;
import modelo.DAOproducto;
import modelo.DAOVenta;
import modelo.Cliente;
import modelo.producto;
import modelo.venta;
import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
/**
 *
 * @author juriel
 */
public class JFrameVenta_Detalle extends javax.swing.JFrame {
    
    private DefaultTableModel modelotablaventa;
    private Object[] objetoventaTable = new Object[6];
    private Double total=0.0;
    private int item= 0;
    private java.sql.Date fech;
    private java.sql.Date fechaI;
    private java.sql.Date fechaF;
    private int cantidad=0;
    private int ventaId=0;
    private int productoid;
 
    
    public JFrameVenta_Detalle() {
        initComponents();
        jTextcantidad.setText("0");
        jDialogcliente.setLocationRelativeTo(null);
        jDialogproducto.setLocationRelativeTo(null);
        jTextidcliente.setEnabled(false);
        jTextIDproducto.setEnabled(false);
        fech= java.sql.Date.valueOf(LocalDate.now());
        jLabelfecha.setText(fech.toString());
        
        modelotablaventa=(DefaultTableModel) jTproductoventa.getModel();
    }
    
    public void limpiarcampo(){
        jTextIDproducto.setText("0");
        jTextdescripcion.setText("");
        jTextprecioproducto.setText("0.0");
        jTextExistencia.setText("0");
        jTextcantidad.setText("0");
    }
    
    private void buscarcliente(String datos)throws SQLException{
        List<Cliente> clientes=new DAOCliente().buscarCliente(datos);
        
        DefaultTableModel modelo=new DefaultTableModel();
        
        String[] columnas={"cliente_id", "Nombre", "Apellido","telefono",
        "direccion"};
        
       modelo.setColumnIdentifiers(columnas);
       for (Cliente cli : clientes){
           String[] renglon = {Integer.toString(cli.getcliente_id()),
               cli.getNombre(),cli.getApellido(), cli.getTelefono(), cli.getDireccion()};
           modelo.addRow(renglon);
       }
       jTablebuscarcliente.setModel(modelo);
    }
    
    
    
    private void buscarproducto(String dato)throws SQLException{
        List<producto> productos = new DAOproducto().buscarproducto(dato);
        DefaultTableModel modelo=new DefaultTableModel();
        String[] columnas ={"producto_id", "descripcion", 
        "precio_produc", "Existencia"};
        
        modelo.setColumnIdentifiers(columnas);
        for(producto pro:productos){
            String[] renglon ={Integer.toString(pro.getProducto_id()),
            pro.getDescripcion(), Double.toString(pro.getPrecio_produc()),
            Integer.toString(pro.getExistencia())};
            modelo.addRow(renglon);
        }
        jTablebuscarProduct.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField13 = new javax.swing.JTextField();
        jDialogproducto = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jTextproduct = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jBAñadir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablebuscarProduct = new javax.swing.JTable();
        jDialogcliente = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextclientebuscar = new javax.swing.JTextField();
        jBcliente = new javax.swing.JButton();
        jBagregarcliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablebuscarcliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextIDproducto = new javax.swing.JTextField();
        jTextdescripcion = new javax.swing.JTextField();
        jBbuscarproducto = new javax.swing.JButton();
        jTextprecioproducto = new javax.swing.JTextField();
        jTextExistencia = new javax.swing.JTextField();
        jTextcantidad = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jBQuitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextidcliente = new javax.swing.JTextField();
        jTextCliente = new javax.swing.JTextField();
        jBCliente = new javax.swing.JButton();
        jLabelfecha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTproductoventa = new javax.swing.JTable();
        jlabeltotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jDialogproducto.setSize(new java.awt.Dimension(600, 600));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Buscar Producto");

        jBBuscar.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBAñadir.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jBAñadir.setText("Añadir");
        jBAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAñadirActionPerformed(evt);
            }
        });

        jTablebuscarProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablebuscarProduct);

        javax.swing.GroupLayout jDialogproductoLayout = new javax.swing.GroupLayout(jDialogproducto.getContentPane());
        jDialogproducto.getContentPane().setLayout(jDialogproductoLayout);
        jDialogproductoLayout.setHorizontalGroup(
            jDialogproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogproductoLayout.createSequentialGroup()
                .addGroup(jDialogproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogproductoLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel4))
                    .addGroup(jDialogproductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jBBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jBAñadir))
                    .addGroup(jDialogproductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogproductoLayout.setVerticalGroup(
            jDialogproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogproductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar)
                    .addComponent(jBAñadir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogcliente.setSize(new java.awt.Dimension(600, 600));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Buscar Clientes");

        jBcliente.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jBcliente.setText("Buscar");
        jBcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclienteActionPerformed(evt);
            }
        });

        jBagregarcliente.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jBagregarcliente.setText("Añadir");
        jBagregarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarclienteActionPerformed(evt);
            }
        });

        jTablebuscarcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTablebuscarcliente);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextclientebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jBcliente)
                        .addGap(18, 18, 18)
                        .addComponent(jBagregarcliente))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextclientebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcliente)
                    .addComponent(jBagregarcliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogclienteLayout = new javax.swing.GroupLayout(jDialogcliente.getContentPane());
        jDialogcliente.getContentPane().setLayout(jDialogclienteLayout);
        jDialogclienteLayout.setHorizontalGroup(
            jDialogclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogclienteLayout.setVerticalGroup(
            jDialogclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jLabel6.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Venta ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 3, 24), new java.awt.Color(102, 102, 255))); // NOI18N

        jTextIDproducto.setBackground(new java.awt.Color(255, 255, 255));
        jTextIDproducto.setText("ID");

        jTextdescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTextdescripcion.setText("Producto");

        jBbuscarproducto.setBackground(new java.awt.Color(255, 255, 255));
        jBbuscarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/buscar.png"))); // NOI18N
        jBbuscarproducto.setText("Buscar");
        jBbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarproductoActionPerformed(evt);
            }
        });

        jTextprecioproducto.setBackground(new java.awt.Color(255, 255, 255));

        jTextExistencia.setBackground(new java.awt.Color(255, 255, 255));

        jTextcantidad.setBackground(new java.awt.Color(255, 255, 255));

        jBAgregar.setBackground(new java.awt.Color(0, 153, 51));
        jBAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/boton-agregar.png"))); // NOI18N
        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBQuitar.setBackground(new java.awt.Color(255, 51, 51));
        jBQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/eliminar (1).png"))); // NOI18N
        jBQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Existencia");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextprecioproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jTextExistencia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextcantidad, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextIDproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextdescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBbuscarproducto)))
                .addGap(25, 25, 25))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIDproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscarproducto))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jBAgregar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jBQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextprecioproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(41, 41, 41))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 3, 24), new java.awt.Color(102, 102, 255))); // NOI18N

        jTextidcliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextidcliente.setText("ID");

        jTextCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextCliente.setText("Cliente");

        jBCliente.setBackground(new java.awt.Color(255, 255, 255));
        jBCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/buscar.png"))); // NOI18N
        jBCliente.setText("Buscar");
        jBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClienteActionPerformed(evt);
            }
        });

        jLabelfecha.setForeground(new java.awt.Color(0, 0, 0));
        jLabelfecha.setText("Fecha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCliente)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelfecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCliente)
                    .addComponent(jTextidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTproductoventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "proucto_id", "cliente_id", "descripcion", "cantidad ", "subtotal", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTproductoventa);

        jlabeltotal.setForeground(new java.awt.Color(0, 0, 0));
        jlabeltotal.setText("Total");

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/boton-agregar.png"))); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/eliminar (1).png"))); // NOI18N

        jButton3.setText("Factura");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlabeltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabeltotal)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarproductoActionPerformed
        // TODO add your handling code here:
        jDialogproducto.setVisible(true);
    }//GEN-LAST:event_jBbuscarproductoActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        if(jTextproduct.getText().contentEquals("")){
               JOptionPane.showMessageDialog(rootPane,
                    "Ingrese texto a buscar");
        }else{
            try{
             String datopro=jTextproduct.getText();
                buscarproducto(datopro);
                jTextproduct.setText("");
            }catch(SQLException ex){
                 Logger.getLogger(JFrameVenta_Detalle.class.getName()).
                        log(Level.SEVERE,null,ex); 
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAñadirActionPerformed
        // TODO add your handling code here:
        int fila =this.jTablebuscarProduct.getSelectedRow();
                if(fila==-1){
                     JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione un registro de la tabla"); 
                }else{
                    try{
                      int id=Integer.parseInt((String)this.jTablebuscarProduct.
                              getValueAt(fila, 0).toString());
                      String des=(String)this.jTablebuscarProduct.getValueAt(fila, 1);
                      float precio=Float.parseFloat((String)this.jTablebuscarProduct.
                              getValueAt(fila, 2).toString());
                      int exi=Integer.parseInt((String)this.jTablebuscarProduct.
                              getValueAt(fila, 3).toString());
                      
                      jTextIDproducto.setText(""+id);
                      jTextdescripcion.setText(des);
                      jTextprecioproducto.setText(""+precio);
                      jTextExistencia.setText(""+exi);
                    }catch(NumberFormatException e){
                         JOptionPane.showMessageDialog(rootPane,
                      "Ocurrio un Error!"+e.getMessage());
                    }
                }
    }//GEN-LAST:event_jBAñadirActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        if(jTextcantidad.getText().contentEquals("0")){
            JOptionPane.showMessageDialog(rootPane,
                    "Escriba la cantidad de producto");
        }else{
            if(Integer.parseInt(jTextcantidad.getText().trim())>
                    Integer.parseInt(jTextExistencia.getText().trim())){
                JOptionPane.showMessageDialog(rootPane,
                        "La cantidad indicada supera la existencia actual"+
                                "del producto");
            }else{
                item+=1;
                
                objetoventaTable[0]=item;
                
                 objetoventaTable[1]= jTextIDproducto.getText().trim();
                objetoventaTable[2]= jTextdescripcion.getText().trim();
                 objetoventaTable[3]=jTextcantidad.getText().trim();
                 objetoventaTable[4]=jTextprecioproducto.getText().trim();
                
                Double subtotal= Double.parseDouble(jTextcantidad.getText().trim())
                        *Double.parseDouble(jTextprecioproducto.getText().trim());
                
                objetoventaTable[5]=subtotal;
                total+=subtotal;
                
                jlabeltotal.setText(total.toString());
                
                modelotablaventa.addRow(objetoventaTable);
                
                limpiarcampo();
                
                
            }
        }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClienteActionPerformed
        // TODO add your handling code here:
        jDialogcliente.setVisible(true);
    }//GEN-LAST:event_jBClienteActionPerformed

    private void jBclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclienteActionPerformed
        // TODO add your handling code here:
        if(jTextclientebuscar.getText().contentEquals("")){
            JOptionPane.showMessageDialog(rootPane,
                    "Ingrese texto a buscar");
        }else{
            try{
                String datocli=jTextclientebuscar.getText();
                buscarcliente(datocli);
                jTextclientebuscar.setText("");
            }catch(SQLException ex){
                 Logger.getLogger(JFrameVenta_Detalle.class.getName()).
                        log(Level.SEVERE,null,ex); 
            }
        }
    }//GEN-LAST:event_jBclienteActionPerformed

    private void jBagregarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarclienteActionPerformed
        // TODO add your handling code here:
        int fila =this.jTablebuscarcliente.getSelectedRow();
        if(fila==-1){
              JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione un registro de la tabla");
        }else{
            try{
                int id=Integer.parseInt((String)this.jTablebuscarcliente.
                        getValueAt(fila, 0).toString());
                String nom=(String)this.jTablebuscarcliente.getValueAt(fila, 1);
                String ape=(String)this.jTablebuscarcliente.getValueAt(fila, 2);
                
                jTextidcliente.setText(""+id);
                jTextCliente.setText(nom+""+ape);
            }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(rootPane, 
                        "Ocurrio un Error!"+e.getMessage());
            }
        }
    }//GEN-LAST:event_jBagregarclienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            guardarventa();
        }catch(SQLException ex){
                Logger.getLogger(JFrameVenta_Detalle.class.getName()).
                        log(Level.SEVERE,null, ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DAOVenta daOventa=new DAOVenta();
        if(ventaId !=0){
         try{
        daOventa.factura(ventaId);
        }catch(JRException ex){
               Logger.getLogger(JFrameVenta_Detalle.class.getName()).
                        log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitarActionPerformed
        // TODO add your handling code here:
         int fila = this.jTproductoventa.getSelectedRow();
        if (fila == -1 ){
            JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione una fila de la tabla");
            
        } else {
            JDialog.setDefaultLookAndFeelDecorated(true);
            int resp = JOptionPane.showConfirmDialog(null, 
                    "¿Está seguro de quitar el producto de la lista?", 
                    "Aceptar", JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE);
            if (resp == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(rootPane, 
                        "No se ha retirado ningún producto");
                
            } else {
                if (resp == JOptionPane.YES_OPTION) {
                    DefaultTableModel temp = (DefaultTableModel)
                            jTproductoventa.getModel();
                 temp.removeRow(fila);
                 for (int i = 0; i < jTproductoventa.getRowCount(); i++) {
                      total = 0.0;
                      total += Double.parseDouble(jTproductoventa.
                              getValueAt(i, 5).toString());
                 }
                 jlabeltotal.setText(total.toString());
             }
                if (resp == JOptionPane.CLOSED_OPTION) {
                    JOptionPane.showMessageDialog(rootPane, 
                            "Ninguna acción realizada");
                }
          }
      }

    }//GEN-LAST:event_jBQuitarActionPerformed

    public void guardarventa()throws SQLException{
        int clienteid;
        
        if (jTextidcliente.getText().contentEquals("")||
                jLabelfecha.getText().contentEquals("")|| 
                jTproductoventa.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, 
              "Se requieren datos del cliente y producto, "
            + "fecha");
            
        } else {
            try{
                
                
                 clienteid = Integer.parseInt(jTextidcliente.getText());
            
                venta vent = new venta(clienteid, fech);
                
                DAOVenta daoventa = new DAOVenta();
               
                if (daoventa.insertarventa(vent)==0){
                    JOptionPane.showMessageDialog(rootPane, 
                            "Registro agregado en venta");
                    
                    ventaId = daoventa.obtenerUltimoventaid();

                } else {
                    JOptionPane.showMessageDialog(rootPane, 
                         "Ha ocurrido un error, no se insertó en venta");
                }
            } catch (HeadlessException | SQLException e){
                 JOptionPane.showMessageDialog(rootPane, 
                         "No se agregaron los registros" + e);
            }
            JOptionPane.showMessageDialog(rootPane,
                    "Registro listo para venta" + ventaId);
            
            guardardetalleventa();//Llamado al método que guarda los detalles
            
           actualizarExistencia();
        } 
    }
    
    
    public void guardardetalleventa()throws SQLException{
        float precioUnitario;
        if(ventaId ==0 || jTproductoventa.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, 
                    "No se a obtenido el numero de la venta o "+
                            "no tienes producto añadido para vender");
        }else{
            for(int i =0 ; i<jTproductoventa.getRowCount(); i++){
                productoid=Integer.parseInt(jTproductoventa.
                        getValueAt(i, 1).toString());
                cantidad=Integer.parseInt(jTproductoventa.
                        getValueAt(i, 3).toString());
                precioUnitario=Float.parseFloat(jTproductoventa.
                        getValueAt(i, 4).toString());
                
                
                venta detalleventa=new venta(ventaId, 
                        productoid, cantidad, precioUnitario);
                
                DAOVenta daodetalleventa=new DAOVenta();
                
                if(daodetalleventa.insertardetalleventa(detalleventa)==0){
                    JOptionPane.showMessageDialog(rootPane, 
                            "Registro agregado a Detalle venta");
                    
                }else{
                   JOptionPane.showMessageDialog(rootPane,
                            "Ha ocurrido un error, no se inserto el Detalle venta");  
                }
            }
        }
    }
        
    public void actualizarExistencia(){
        int existenciaActual;
        int nuevaExistencia;
        
        for(int i=0; i<jTproductoventa.getRowCount(); i++){
            productoid=Integer.parseInt(jTproductoventa.
                    getValueAt(i, 1).toString());
            cantidad = Integer.parseInt(jTproductoventa.
                    getValueAt(i, 3).toString());
            
            DAOproducto dAOproducto=new DAOproducto();
            
            try{
                List<producto> p=dAOproducto.buscarproducto(String.valueOf
        (productoid).toString());
                existenciaActual=p.get(0).getExistencia();
                nuevaExistencia=existenciaActual-cantidad;
                producto pro=new producto(productoid,  nuevaExistencia);
                DAOVenta daoventa=new DAOVenta();
                if(daoventa.actualizarExistenciaProducto(pro)==0){
                      JOptionPane.showMessageDialog(rootPane, 
                            "Existencia actualizada");
                }
            }catch(SQLException ex){
                Logger.getLogger(JFrameVenta_Detalle.class.getName()).
                        log(Level.SEVERE,null, ex);
            }
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta_Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameVenta_Detalle().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBAñadir;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCliente;
    private javax.swing.JButton jBQuitar;
    private javax.swing.JButton jBagregarcliente;
    private javax.swing.JButton jBbuscarproducto;
    private javax.swing.JButton jBcliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialogcliente;
    private javax.swing.JDialog jDialogproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelfecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablebuscarProduct;
    private javax.swing.JTable jTablebuscarcliente;
    private javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextExistencia;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextIDproducto;
    private javax.swing.JTextField jTextcantidad;
    private javax.swing.JTextField jTextclientebuscar;
    private javax.swing.JTextField jTextdescripcion;
    private javax.swing.JTextField jTextidcliente;
    private javax.swing.JTextField jTextprecioproducto;
    private javax.swing.JTextField jTextproduct;
    private javax.swing.JTable jTproductoventa;
    private javax.swing.JLabel jlabeltotal;
    // End of variables declaration//GEN-END:variables
}
