 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.HeadlessException;
import modelo.producto;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.sql.CallableStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.StringValueExp;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DAOCategoria;
import modelo.DAOMarca;
import modelo.DAOproducto;
import modelo.categoria;
import modelo.marca;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author juriel
 */
public class JFrameProducto extends javax.swing.JFrame {

    /**
     * Creates new form Producto
     */
    public JFrameProducto() throws SQLException {
        initComponents();
        jTextId.setEnabled(false);
        Obtenerdatos();
        jTextmarca.setEnabled(false);
        jTextcategoria.setEnabled(false);
        jTextcategoria.setEnabled(false);
        llenarcombo();
        llenarcombo2();
    }

    public void llenarcombo() throws SQLException {
        List<marca> marcas = new DAOMarca().obtenerDatos();
        for (int i = 0; i < marcas.size(); i++) {
            jCombomarca.addItem(new marca(marcas.get(i).getMarca_id(),
                    marcas.get(i).getNombre_marca()));
        }
        int id = jCombomarca.getItemAt(jCombomarca.getSelectedIndex()).getMarca_id();
        jTextmarca.setText("" + id);
    }

    public void llenarcombo2() throws SQLException {
        List<categoria> categorias = new DAOCategoria().obtenerDatos();
        for (int i = 0; i < categorias.size(); i++) {
            jCombocategoria.addItem(new categoria(categorias.get(i).getCategoria_id(),
                    categorias.get(i).getDescripcion()));
        }
        int id = jCombocategoria.getItemAt(jCombocategoria.getSelectedIndex()).getCategoria_id();
        jTextcategoria.setText("" + id);
    }

    private void limpiarcampos() {
        jTextId.setText("");
        jTextdescripcion.setText("");
        jFormattedcantidad.setText("");
        jFormattedprecio1.setText("");
        jFormattedexistencia.setText("");
    }
    
    private void actualizarpro()throws SQLException{
        int id=Integer.parseInt(this.jTextId.getText().toString());
        String des=this.jTextdescripcion.getText();
        int cant=Integer.parseInt(this.jFormattedcantidad.getText().toString());
        double precio=Double.parseDouble(this.jFormattedprecio1.getText().toString());
        int exi=Integer.parseInt(this.jFormattedexistencia.getText().toString());
        
        
        producto pro=new producto(id, des, cant, precio, exi);
        
        DAOproducto dao=new DAOproducto();
        int res=dao.Actualizar(pro);
        if(res==0){
            JOptionPane.showMessageDialog(rootPane,
                       "¡Se a actualizado!");
        }else{
            JOptionPane.showMessageDialog(rootPane, 
                       "Algo salío mal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedprecio1 = new javax.swing.JFormattedTextField();
        jButtonagregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jFormattedcantidad = new javax.swing.JFormattedTextField();
        jTextdescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCombomarca = new javax.swing.JComboBox<>();
        jCombocategoria = new javax.swing.JComboBox<>();
        jTextmarca = new javax.swing.JTextField();
        jTextcategoria = new javax.swing.JTextField();
        jFormattedexistencia = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableproduc = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextbuscarproduct = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cantidad");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descripción");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio Producto");

        jFormattedprecio1.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedprecio1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.##"))));

        jButtonagregar.setBackground(new java.awt.Color(0, 153, 51));
        jButtonagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/boton-agregar.png"))); // NOI18N
        jButtonagregar.setText("Agregar");
        jButtonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonagregarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID");

        jTextId.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jFormattedcantidad.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedcantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        jTextdescripcion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Existencia");

        jCombomarca.setBackground(new java.awt.Color(255, 255, 255));
        jCombomarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombomarcaItemStateChanged(evt);
            }
        });
        jCombomarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombomarcaActionPerformed(evt);
            }
        });

        jCombocategoria.setBackground(new java.awt.Color(255, 255, 255));
        jCombocategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombocategoriaItemStateChanged(evt);
            }
        });

        jFormattedexistencia.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedexistencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonagregar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCombomarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCombocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFormattedexistencia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedprecio1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jFormattedcantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextdescripcion, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombomarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombocategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonagregar))
                .addGap(45, 45, 45))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTableproduc.setAutoCreateRowSorter(true);
        jTableproduc.setBackground(new java.awt.Color(255, 255, 255));
        jTableproduc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableproduc);

        jButton5.setBackground(new java.awt.Color(0, 153, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/editar (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 102, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/actualizar (1).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(63, 218, 132));
        jPanel3.setForeground(new java.awt.Color(0, 153, 102));

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Dollar");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Store");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jTextbuscarproduct.setBackground(new java.awt.Color(255, 255, 255));
        jTextbuscarproduct.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextbuscarproduct.setText("Buscar Producto");

        jBbuscar.setBackground(new java.awt.Color(255, 255, 255));
        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/buscar.png"))); // NOI18N
        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Producto");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/product.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 684, Short.MAX_VALUE)
                .addComponent(jTextbuscarproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBbuscar)
                .addGap(62, 62, 62))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextbuscarproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9))
                    .addComponent(jBbuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCombomarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombomarcaItemStateChanged
        // TODO add your handling code here:
        int id = jCombomarca.getItemAt(jCombomarca.getSelectedIndex()).getMarca_id();
        jTextmarca.setText("" + id);
    }//GEN-LAST:event_jCombomarcaItemStateChanged

    private void jCombocategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombocategoriaItemStateChanged
        // TODO add your handling code here:
        int id = jCombocategoria.getItemAt(jCombocategoria.getSelectedIndex()).getCategoria_id();
        jTextcategoria.setText("" + id);
    }//GEN-LAST:event_jCombocategoriaItemStateChanged

    private void jButtonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonagregarActionPerformed

        try {
            String descri = jTextdescripcion.getText();
            int cant = Integer.parseInt(jFormattedcantidad.getText());
            double preciopro = Double.parseDouble(jFormattedprecio1.getText());
            int existe= Integer.parseInt(jFormattedexistencia.getText());
            int categ = Integer.parseInt(jTextcategoria.getText());
            int marc = Integer.parseInt(jTextmarca.getText());

            if (descri.contentEquals("") || jFormattedcantidad.getText().contentEquals("")
                    || jFormattedprecio1.getText().contentEquals("")
                    || jFormattedexistencia.getText().contentEquals("")
                    || jTextcategoria.getText().contentEquals("") || jTextmarca.getText().contentEquals("")) {

                JOptionPane.showMessageDialog(rootPane,
                        "Necesita llenar todos los campos");
            } else {
                try {

                    producto pro = new producto(descri, cant,
                            preciopro,existe, marc, categ);

                    DAOproducto dao = new DAOproducto();

                    if (dao.insertar(pro) == 0) {
                        JOptionPane.showMessageDialog(rootPane,
                                "Ya se a agregado");
                    }
                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(rootPane,
                            "No se agrego otros Datos");
                }
            }
            Obtenerdatos();
            limpiarcampos();

        } catch (SQLException ex) {
            Logger.getLogger(JFrameCliente.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonagregarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiarcampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int fila =this.jTableproduc.getSelectedRow();
        if(fila==-1){
             JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione un registro");
        }else{
            try{
                int id=Integer.parseInt((String)this.jTableproduc.
                        getValueAt(fila, 0).toString());
                String des=(String)this.jTableproduc.getValueAt(fila, 1);
                int cant=Integer.parseInt((String)this.jTableproduc.
                        getValueAt(fila, 2).toString());
                float precio=Float.parseFloat((String)this.jTableproduc.
                        getValueAt(fila, 3).toString());
                int exi=Integer.parseInt((String)this.jTableproduc.
                        getValueAt(fila, 5).toString());
                
                
                
                
                jTextId.setText(""+id);
                jTextdescripcion.setText(des);
                jFormattedcantidad.setText(""+cant);
                jFormattedprecio1.setText(""+precio);
                jFormattedexistencia.setText(""+exi);
               
                
            }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(rootPane,
                        "¡Ocurrio un error!"+e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            actualizarpro();
        }catch(SQLException ex){
                 Logger.getLogger(JFrameProducto.class.getName()).
                    log(Level.SEVERE,null,ex);
        }
        try{
            Obtenerdatos();
        }catch(SQLException ex){
                 Logger.getLogger(JFrameProducto.class.getName()).
                    log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        if(jTextbuscarproduct.getText().contentEquals("")){
             JOptionPane.showMessageDialog(rootPane,
              "Ingrese texto en el campo");
        }else{
            try{
                String datopro=jTextbuscarproduct.getText();
                buscarproducto(datopro);
                jTextbuscarproduct.setText("");
            }catch(SQLException ex){
             Logger.getLogger(JFrameProducto.class.getName()).
                        log(Level.SEVERE,null,ex); 
        }
        }
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jCombomarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombomarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombomarcaActionPerformed

    private void Obtenerdatos() throws SQLException {
        List<producto> productos = new DAOproducto().ObtenerDatos();

        DefaultTableModel modelo = new DefaultTableModel();

        String[] columnas = {"producto_id", "descripcion", "cantidad", "precio_produc",
            "precio_compra", "marca_id", "categoria_id"};

        modelo.setColumnIdentifiers(columnas);
        for (producto pro : productos) {
            String[] renglon = {Integer.toString(pro.getProducto_id()),
                (String) pro.getDescripcion(),
                Integer.toString(pro.getCantidad()),
                Double.toString(pro.getPrecio_produc()),
                Float.toString(pro.getExistencia()),
                Integer.toString(pro.getMarca_id()),
                Integer.toString(pro.getCategoria_id())};
            modelo.addRow(renglon);
        }
        jTableproduc.setModel(modelo);
    }
    
    public void buscarproducto(String dato)throws SQLException{
        List<producto> productos=new DAOproducto().buscarproducto(dato);
        DefaultTableModel modelo=new DefaultTableModel();
        String[] columnas={"producto_id", "descripcion", "cantidad", "precio_produc",
            "precio_compra", "marca_id", "categoria_id"};
        
        modelo.setColumnIdentifiers(columnas);
        for(producto pr:productos){
            String[] renglon ={Integer.toString(pr.getProducto_id()),
            pr.getDescripcion(), Integer.toString(pr.getCantidad()),
            Double.toString(pr.getPrecio_produc()),Integer.toString(pr.getExistencia())
            };
            modelo.addRow(renglon);
            
        }
        jTableproduc.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameProducto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFrameProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonagregar;
    private javax.swing.JComboBox<categoria> jCombocategoria;
    private javax.swing.JComboBox<marca> jCombomarca;
    private javax.swing.JFormattedTextField jFormattedcantidad;
    private javax.swing.JFormattedTextField jFormattedexistencia;
    private javax.swing.JFormattedTextField jFormattedprecio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableproduc;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextbuscarproduct;
    private javax.swing.JTextField jTextcategoria;
    private javax.swing.JTextField jTextdescripcion;
    private javax.swing.JTextField jTextmarca;
    // End of variables declaration//GEN-END:variables
}
