/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.DAOCategoria;
import modelo.DAOMarca;
import modelo.categoria;
import modelo.marca;
/**
 *
 * @author juriel
 */
public class jFramemarca_categoria extends javax.swing.JFrame {

    /**
     * Creates new form jFramemarca_categoria
     */
    public jFramemarca_categoria() throws SQLException {
        initComponents();
        jTextID.setEnabled(false);
        jTextIDcategoria.setEnabled(false);
        obtenerDatos();
        obtenerDatos2();
    }
    
    private void limpiarcampos(){
        jTextID.setText("");
        jTextnombre_marca.setText("");
       
    }
    private void limpiarcampos2(){
        jTextIDcategoria.setText("");
        jTextdescripcion.setText("");
    }

    private void obtenerDatos()throws SQLException{
        List<marca> marcas=new DAOMarca().obtenerDatos();
        DefaultTableModel modelo=new DefaultTableModel();
       
        String[] columnas ={"marca_id", "nombre_marca"};
    
        modelo.setColumnIdentifiers(columnas);
        for(marca mr:marcas){
           
            String[] renglon ={Integer.toString(mr.getMarca_id()),
                mr.getNombre_marca()};
            modelo.addRow(renglon);
             
        }
        jTablemarca.setModel(modelo);
    }
    
    private void obtenerDatos2()throws SQLException{
        List<categoria> categorias =new DAOCategoria().obtenerDatos();
        
        DefaultTableModel  modelo=new DefaultTableModel();
        
        String[] columnas={"categoria_id", "descripcion"};
        
        modelo.setColumnIdentifiers(columnas);
        for(categoria ct:categorias){
            String[] renglon={Integer.toString(ct.getCategoria_id()),
                ct.getDescripcion()};
            modelo.addRow(renglon);
            }
        
        jTablecategoria.setModel(modelo);
    }
    
    private void actualizarcategoria() throws SQLException{
        int idcate=Integer.parseInt(this.jTextIDcategoria.getText());
        String des=this.jTextdescripcion.getText();
        
        categoria cate=new categoria(idcate, des);
        
        DAOCategoria dao=new DAOCategoria();
        int res= dao.Actualizar(cate);
        if(res==0){
            JOptionPane.showMessageDialog(rootPane, 
                    "¡Se a Actualizado!");
        }else{
            JOptionPane.showMessageDialog(rootPane, 
                    "Algo salío mal");
           
        }
    }
    
    private void actualizarmarca()throws SQLException{
        int idmar=Integer.parseInt(this.jTextID.getText());
        String nombr=this.jTextnombre_marca.getText();
        
        marca mar=new marca(idmar, nombr);
        
        DAOMarca dao=new DAOMarca();
        int res=dao.Actualizar(mar);
        if(res==0){
            JOptionPane.showMessageDialog(rootPane, 
                    "¡Se a actualizado!");
        }else {
            JOptionPane.showMessageDialog(rootPane, 
                       "Algo salío mal");
        }
                
    }
    
    private void buscarcategoria(String dato)throws SQLException{
        List<categoria> categoria=new DAOCategoria().buscarcategoria(dato);
        
        DefaultTableModel modelo= new DefaultTableModel();
        String[] columnas={"categoria_id", "descripcion"};
        
        modelo.setColumnIdentifiers(columnas);
        
        for(categoria cat:categoria){
            String[] renglon={Integer.toString(cat.getCategoria_id()),
            cat.getDescripcion()};
            
            modelo.addRow(renglon);
        }
        jTablecategoria.setModel(modelo);
    }
    
    private void buscarmarca(String dato)throws SQLException{
        List<marca> marcas=new DAOMarca().buscarmarca(dato);
        
        DefaultTableModel modelo= new DefaultTableModel();
        String[] columnas={"marca_id", "nombre_marca"};
        
        modelo.setColumnIdentifiers(columnas);
        
        for(marca mr : marcas){
            String[] renglon={Integer.toString(mr.getMarca_id()),
            mr.getNombre_marca()};
            
            modelo.addRow(renglon);
        }
        jTablemarca.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBActualizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablecategoria = new javax.swing.JTable();
        jBEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jBbuscar1 = new javax.swing.JButton();
        jTextbuscategoria = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextnombre_marca = new javax.swing.JTextField();
        jBagregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtextfielbuscarmarca = new javax.swing.JTextField();
        jBbuscarmarca = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextdescripcion = new javax.swing.JTextField();
        jBagregar1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextIDcategoria = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jBActualizar1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablemarca = new javax.swing.JTable();
        jBEditar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(63, 218, 132));
        jPanel3.setForeground(new java.awt.Color(0, 153, 102));

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Dollar");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Store");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jBActualizar.setBackground(new java.awt.Color(102, 102, 255));
        jBActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/actualizar (1).png"))); // NOI18N
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jTablecategoria.setAutoCreateRowSorter(true);
        jTablecategoria.setBackground(new java.awt.Color(255, 255, 255));
        jTablecategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablecategoria);

        jBEditar.setBackground(new java.awt.Color(0, 153, 51));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/editar (1).png"))); // NOI18N
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("REGISTROS");

        jBbuscar1.setBackground(new java.awt.Color(255, 255, 255));
        jBbuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/buscar.png"))); // NOI18N
        jBbuscar1.setText("Buscar");
        jBbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscar1ActionPerformed(evt);
            }
        });

        jTextbuscategoria.setBackground(new java.awt.Color(255, 255, 255));
        jTextbuscategoria.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextbuscategoria.setText("Buscar categoria");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextbuscategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBbuscar1)
                .addGap(18, 18, 18)
                .addComponent(jBEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBActualizar)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBbuscar1)
                        .addComponent(jTextbuscategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marca", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 51, 102))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre Marca");

        jTextnombre_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextnombre_marcaKeyTyped(evt);
            }
        });

        jBagregar.setBackground(new java.awt.Color(0, 153, 51));
        jBagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/boton-agregar.png"))); // NOI18N
        jBagregar.setText("Agregar");
        jBagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID");

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jTextnombre_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jTextID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBagregar)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextnombre_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBagregar))
                .addGap(280, 280, 280))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jLabel10.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Marca/Categoria");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/apoyo.png"))); // NOI18N

        jtextfielbuscarmarca.setBackground(new java.awt.Color(255, 255, 255));

        jBbuscarmarca.setBackground(new java.awt.Color(255, 255, 255));
        jBbuscarmarca.setText("Buscar");
        jBbuscarmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarmarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtextfielbuscarmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBbuscarmarca)
                        .addGap(130, 130, 130))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jtextfielbuscarmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBbuscarmarca)))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripción");

        jTextdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextdescripcionKeyTyped(evt);
            }
        });

        jBagregar1.setBackground(new java.awt.Color(0, 153, 51));
        jBagregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/boton-agregar.png"))); // NOI18N
        jBagregar1.setText("Agregar");
        jBagregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregar1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ID");

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(jTextdescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jTextIDcategoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBagregar1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextIDcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBagregar1))
                .addGap(267, 267, 267))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jBActualizar1.setBackground(new java.awt.Color(102, 102, 255));
        jBActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/actualizar (1).png"))); // NOI18N
        jBActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizar1ActionPerformed(evt);
            }
        });

        jTablemarca.setAutoCreateRowSorter(true);
        jTablemarca.setBackground(new java.awt.Color(255, 255, 255));
        jTablemarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane4.setViewportView(jTablemarca);

        jBEditar1.setBackground(new java.awt.Color(0, 153, 51));
        jBEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/editar (1).png"))); // NOI18N
        jBEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditar1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("REGISTROS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(158, 158, 158)
                        .addComponent(jBEditar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBActualizar1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBActualizar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(301, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(300, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextnombre_marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextnombre_marcaKeyTyped
        // TODO add your handling code here:
        char car=evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car >'Z')
            && car !='á'
            && car !='é'
            && car !='í'
            && car !='ó'
            && car !='ú'
            && car !='Á'
            && car !='É'
            && car !='Í'
            && car !='Ó'
            && car !='Ú'
            && car !='Ü'
            && car !='ü'
            && car !='Ñ'
            && car !='ñ'
            && car !=(char) KeyEvent.VK_SPACE){
            evt.consume();

        }
    }//GEN-LAST:event_jTextnombre_marcaKeyTyped

    private void jTextdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextdescripcionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdescripcionKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         // TODO add your handling code here:
         limpiarcampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarActionPerformed
        // TODO add your handling code here:
        try{
            String nomb=jTextnombre_marca.getText();
            
            if (nomb.contentEquals("")){
                 JOptionPane.showMessageDialog(rootPane, 
                        "Necesita llenar todos los campos  ");
            }else{
                try{
                    marca mr=new marca(nomb);
                    DAOMarca dao=new DAOMarca();
                    if(dao.insertar(mr) == 0){
                         JOptionPane.showMessageDialog(rootPane,
                                "Ya se a agregado");
                    }
                }catch(HeadlessException | SQLException e){
                     JOptionPane.showMessageDialog(rootPane,
                            "No se agrego otros Datos");
                }
               
            }
             obtenerDatos();
                limpiarcampos();
                    }catch(SQLException ex){
            Logger.getLogger(jFramemarca_categoria.class.getName()).
                    log(Level.SEVERE,null, ex );
                    }
    }//GEN-LAST:event_jBagregarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        limpiarcampos2();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBagregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregar1ActionPerformed
        // TODO add your handling code here:
        try{
            String descrip=jTextdescripcion.getText();
             if(descrip.contentEquals("")){
                 JOptionPane.showMessageDialog(rootPane, 
                         "Todos los campos son obligatorios");
             }else{
                 try{
                     
                     categoria cat=new categoria(descrip);
                     DAOCategoria dao=new DAOCategoria();
                     if(dao.insertar(cat) == 0){
                         JOptionPane.showMessageDialog(rootPane, 
                                 "Registros agregados");
                         
                     }
                 }catch(HeadlessException | SQLException e){
                             JOptionPane.showMessageDialog(rootPane, 
                                     "No se a agregado el registro");
                             }
             }
             obtenerDatos2();
             limpiarcampos2();
        }catch(SQLException ex){
             Logger.getLogger(jFramemarca_categoria.class.getName()). 
                    log(Level.SEVERE, null,ex);
        }
    }//GEN-LAST:event_jBagregar1ActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        int fila =this.jTablecategoria.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione un Registro");
            
        }else {
            try{
                int idcat=Integer.parseInt((String)this.jTablecategoria.
                        getValueAt(fila, 0).toString());
                String desc=(String)this.jTablecategoria.getValueAt(fila, 1);
                
                jTextIDcategoria.setText(""+idcat);
                jTextdescripcion.setText(desc);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, 
                        "¡Ocurrio un error!"+e.getMessage());
            }
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditar1ActionPerformed
        // TODO add your handling code here:
        int fila =this.jTablemarca.getSelectedRow();
        if(fila==-1){
             JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione un registro");
        }else{
            try{
                int idmar=Integer.parseInt((String)this.jTablemarca.
                        getValueAt(fila, 0).toString());
                String nombr=(String)this.jTablemarca.getValueAt(fila, 1);
                
                jTextID.setText(""+idmar);
                jTextnombre_marca.setText(nombr);
            }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(rootPane,
                        "¡Ocurrio un error!"+e.getMessage());
            }
        }
    }//GEN-LAST:event_jBEditar1ActionPerformed

    private void jBActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizar1ActionPerformed
        // TODO add your handling code here:
        try{
            actualizarmarca();
        }catch(SQLException ex){
                Logger.getLogger(jFramemarca_categoria.class.getName()).
                    log(Level.SEVERE,null,ex); 
            }
        try{
            obtenerDatos();
        }catch(SQLException ex){
                Logger.getLogger(jFramemarca_categoria.class.getName()).
                    log(Level.SEVERE,null,ex); 
            }
        
    }//GEN-LAST:event_jBActualizar1ActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
        try{
            actualizarcategoria();
           
        }catch(SQLException ex){
                Logger.getLogger(jFramemarca_categoria.class.getName()).
                    log(Level.SEVERE,null,ex); 
            }
        try{
            obtenerDatos2();
        }catch(SQLException ex){
                Logger.getLogger(jFramemarca_categoria.class.getName()).
                    log(Level.SEVERE,null,ex); 
            }
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscar1ActionPerformed
        // TODO add your handling code here:
        if(jTextbuscategoria.getText().contentEquals("")){
            JOptionPane.showMessageDialog(rootPane, 
                    "Ingrese la categoria a buscar");
            
        }else{
            try{
                String daocat=jTextbuscategoria.getText();
                buscarcategoria(daocat);
                jTextbuscategoria.setText("");
            }catch(SQLException ex){
               Logger.getLogger(jFramemarca_categoria.class.getName()).
                        log(Level.SEVERE,null,ex);  
            }
        }
    }//GEN-LAST:event_jBbuscar1ActionPerformed

    private void jBbuscarmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarmarcaActionPerformed
        // TODO add your handling code here:
         if(jtextfielbuscarmarca.getText().contentEquals("")){
            JOptionPane.showMessageDialog(rootPane, 
                    "ingrese la marca a buscar");
         }else{
            try{
                String daomar=jtextfielbuscarmarca.getText();
                buscarmarca(daomar);
                jtextfielbuscarmarca.setText("");
            }catch(SQLException ex){
               Logger.getLogger(jFramemarca_categoria.class.getName()).
                        log(Level.SEVERE,null,ex);  
            }
        }
    }//GEN-LAST:event_jBbuscarmarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramemarca_categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramemarca_categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramemarca_categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramemarca_categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jFramemarca_categoria().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(jFramemarca_categoria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBActualizar1;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEditar1;
    private javax.swing.JButton jBagregar;
    private javax.swing.JButton jBagregar1;
    private javax.swing.JButton jBbuscar1;
    private javax.swing.JButton jBbuscarmarca;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablecategoria;
    private javax.swing.JTable jTablemarca;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextIDcategoria;
    private javax.swing.JTextField jTextbuscategoria;
    private javax.swing.JTextField jTextdescripcion;
    private javax.swing.JTextField jTextnombre_marca;
    private javax.swing.JTextField jtextfielbuscarmarca;
    // End of variables declaration//GEN-END:variables
}
