/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.HeadlessException;
import modelo.Cliente;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.sql.CallableStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DAOCliente;

/**
 *
 * @author juriel
 */
public class JFrameCliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public JFrameCliente() throws SQLException{
        initComponents();
        jTextID.setEnabled(false);
        obtenerDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtexttelefono = new javax.swing.JFormattedTextField();
        jTextnombre = new javax.swing.JTextField();
        jTextapellido = new javax.swing.JTextField();
        jTextdireccion = new javax.swing.JTextField();
        jBagregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextbuscar = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBActualizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablecliente = new javax.swing.JTable();
        jBBorrar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(63, 218, 132));
        jPanel3.setForeground(new java.awt.Color(0, 153, 102));

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Dollar");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Store");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Apellido");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Télefono ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dirección");

        jtexttelefono.setBackground(new java.awt.Color(255, 255, 255));
        try {
            jtexttelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTextnombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnombreActionPerformed(evt);
            }
        });
        jTextnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextnombreKeyTyped(evt);
            }
        });

        jTextapellido.setBackground(new java.awt.Color(255, 255, 255));
        jTextapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextapellidoKeyTyped(evt);
            }
        });

        jTextdireccion.setBackground(new java.awt.Color(255, 255, 255));

        jBagregar.setBackground(new java.awt.Color(0, 153, 51));
        jBagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/boton-agregar.png"))); // NOI18N
        jBagregar.setText("Agregar");
        jBagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID");

        jTextID.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBagregar))
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jTextapellido)
                    .addComponent(jTextnombre)
                    .addComponent(jTextID)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextdireccion)
                    .addComponent(jtexttelefono)
                    .addComponent(jLabel1))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtexttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBagregar)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jTextbuscar.setBackground(new java.awt.Color(255, 255, 255));
        jTextbuscar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextbuscar.setText("Buscar Cliente");

        jBbuscar.setBackground(new java.awt.Color(255, 255, 255));
        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/buscar.png"))); // NOI18N
        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cliente ");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/customer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBbuscar)
                        .addGap(265, 265, 265))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBbuscar)
                        .addComponent(jTextbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jBActualizar.setBackground(new java.awt.Color(102, 102, 255));
        jBActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/actualizar (1).png"))); // NOI18N
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jTablecliente.setAutoCreateRowSorter(true);
        jTablecliente.setBackground(new java.awt.Color(255, 255, 255));
        jTablecliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablecliente);

        jBBorrar.setBackground(new java.awt.Color(255, 51, 51));
        jBBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/eliminar (1).png"))); // NOI18N
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        jBEditar.setBackground(new java.awt.Color(0, 153, 51));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/editar (1).png"))); // NOI18N
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("REGISTROS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(108, 108, 108)
                        .addComponent(jBEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBActualizar)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       private void obtenerDatos() throws SQLException{
        
        List<Cliente> clientes = new DAOCliente().ObtenerDatos();
        
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        String[] columnas={"cliente_id", "Nombre","Apellido",
            "telefono","direccion" };
        
        modelo.setColumnIdentifiers(columnas);
        for (Cliente cl : clientes){
            
            String[] renglon ={Integer.toString(cl.getcliente_id()),
                cl.getNombre(),cl.getApellido(),cl.getTelefono(),
                cl.getDireccion()};
            modelo.addRow(renglon);
        }
        jTablecliente.setModel(modelo);
    }
       
       private void buscarcliente(String datos)throws SQLException{
           List<Cliente> clientes=new DAOCliente().buscarCliente(datos);
           
           DefaultTableModel modelo=new DefaultTableModel();
           String[] columnas={"cliente_id", "Nombre", "Apellido","telefono",
        "direccion"};
           
           modelo.setColumnIdentifiers(columnas);
           for(Cliente cli:clientes){
               String[] renglon={Integer.toString(cli.getcliente_id()),
               cli.getNombre(), cli.getApellido(),cli.getTelefono()
               ,cli.getDireccion()};
               modelo.addRow(renglon);
           }
           jTablecliente.setModel(modelo);
       }
       
       private void limpiarcampor(){
           jTextID.setText("");
           jTextnombre.setText("");
           jTextapellido.setText("");
           jtexttelefono.setText("");
           jTextdireccion.setText("");
    
}
       public void Actualizarcliente()throws SQLException{
           int id=Integer.parseInt(this.jTextID.getText());
           String nomb=this.jTextnombre.getText();
           String apell=this.jTextapellido.getText();
           String tele=this.jtexttelefono.getText();
           String direc=this.jTextdireccion.getText();
      
           Cliente cl=new Cliente(id,nomb, apell,
                   tele, direc);
           DAOCliente dao=new DAOCliente();
           int res= dao.Actualizar(cl);
           if(res == 0){
               JOptionPane.showMessageDialog(rootPane,
                       "¡Se a actualizado!");
               
           }else{
               JOptionPane.showMessageDialog(rootPane, 
                       "Algo salío mal");
           }
         
       }
    
        
       
     
           
    
    
    
    
    private void jTextnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextnombreKeyTyped
        // TODO add your handling code here:
        char car=evt.getKeyChar();
        if((car<'a' || car>'z')&& (car<'A' || car >'Z')
            && car !='á'
            && car !='é'
            && car !='í'
            && car !='ó'
            && car !='ú'
            && car !='Á'
            && car !='É'
            && car !='Í'
            && car !='Ó'
            && car !='Ú'
            && car !='Ü'
            && car !='ü'
            && car !='Ñ'
            && car !='ñ'
            && car !=(char) KeyEvent.VK_SPACE){
            evt.consume();

        }
    }//GEN-LAST:event_jTextnombreKeyTyped

    private void jTextapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextapellidoKeyTyped
        // TODO add your handling code here:
        char car=evt.getKeyChar();
        if ((car<'a' || car>'z')&&(car<'A'||car>'Z')
            && car !='á'
            && car !='é'
            && car !='í'
            && car !='ó'
            && car !='ú'
            && car !='Á'
            && car !='É'
            && car !='Í'
            && car !='Ó'
            && car !='Ú'
            && car !='Ü'
            && car !='ü'
            && car !='Ñ'
            && car !='ñ'
            && car !=(char) KeyEvent.VK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_jTextapellidoKeyTyped

    private void jBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarActionPerformed
        // TODO add your handling code here:
        try{
            String nombr=jTextnombre.getText();
            String apell=jTextapellido.getText();
            String tele=jtexttelefono.getText();
            String direc=jTextdireccion.getText();
            
            if(nombr.contentEquals("")|| apell.contentEquals("")
                    ||tele.contentEquals("")||direc.contentEquals("")){
                JOptionPane.showMessageDialog(rootPane, 
                        "Necesita llenar todos los campos  ");
            }else {
                try{
                    Cliente cl=new Cliente(nombr, apell, tele, direc);
                    DAOCliente dao=new DAOCliente();
                    if(dao.insertar(cl) == 0){
                        JOptionPane.showMessageDialog(rootPane,
                                "Ya se a agregado");
                        
                    }            
                }catch(HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(rootPane,
                            "No se agrego otros Datos");
                }
            }
            obtenerDatos();
            limpiarcampor();
        }catch(SQLException ex){
            Logger.getLogger(JFrameCliente.class.getName()).
                    log(Level.SEVERE,null, ex );
        }
    }//GEN-LAST:event_jBagregarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        limpiarcampor();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed

            try{
                Actualizarcliente();
            }catch(SQLException ex){
                Logger.getLogger(JFrameCliente.class.getName()).
                    log(Level.SEVERE,null,ex); 
            }
            try{
                obtenerDatos();
            }catch(SQLException ex){
                 Logger.getLogger(JFrameCliente.class.getName()).
                    log(Level.SEVERE,null,ex);
            }
        limpiarcampor();
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
          int fila=this.jTablecliente.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(rootPane, 
                    "Seleccione un registro");
        }else{
            try{
                int id =Integer.parseInt((String)this.jTablecliente.
                        getValueAt(fila, 0).toString());
                String nomb=(String)this.jTablecliente.getValueAt(fila, 1);
                String apell=(String)this.jTablecliente.getValueAt(fila, 2);
                String tele=(String)this.jTablecliente.getValueAt(fila, 3);
                String dire=(String)this.jTablecliente.getValueAt(fila, 4).toString();
                
                jTextID.setText(""+id);
                jTextnombre.setText(nomb);
                jTextapellido.setText(apell);
                jtexttelefono.setText(tele);
                jTextdireccion.setText(dire);
                
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane,
                        "¡Ocurrio un error!"+e.getMessage());
            }
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:
          int fila=this.jTablecliente.getSelectedRow();
       if(fila==-1){
       JOptionPane.showMessageDialog(rootPane,
               "Selecione un registro");
       }else{
           JDialog.setDefaultLookAndFeelDecorated(true);
           int resp= JOptionPane.showConfirmDialog(null,
                   "¿Estas seguro que quieres eliminarlo?", 
                   "Aceptar",JOptionPane.YES_NO_OPTION,
                   JOptionPane.QUESTION_MESSAGE);
           if(resp==JOptionPane.NO_OPTION){
              JOptionPane.showMessageDialog(rootPane,
                      "Registro no borrado");
              
           }else{
               
               if(resp==JOptionPane.YES_OPTION){
                   try{
                   int id =Integer.parseInt((String)
                           this.jTablecliente.getValueAt( fila,0).toString());
                   DAOCliente dao= new DAOCliente();
                   dao.delete(id);
                   obtenerDatos();
                   
               }catch(SQLException ex){
                       Logger.getLogger(JFrameCliente.class.getName()).
                    log(Level.SEVERE,null,ex); 
                       }
               }
           }
           if (resp==JOptionPane.CLOSED_OPTION){
               JOptionPane.showMessageDialog(rootPane, 
                       "Ninguna accion realizada");
           }
       }
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
    if(jTextbuscar.getText().contentEquals("")){
      JOptionPane.showMessageDialog(rootPane,
              "Ingrese texto en el campo");
    }else{
        try{
            String datocli=jTextbuscar.getText();
            buscarcliente(datocli);
            jTextbuscar.setText("");
        }catch(SQLException ex){
             Logger.getLogger(JFrameCliente.class.getName()).
                        log(Level.SEVERE,null,ex); 
        }
    }
            
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jTextnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                      new JFrameCliente().setVisible(true);
                }catch (SQLException ex) {
                    Logger.getLogger(JFrameCliente.
                            class.getName()).log(Level.SEVERE, null, ex);
                }
              
                 
                    
                }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBagregar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablecliente;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextapellido;
    private javax.swing.JTextField jTextbuscar;
    private javax.swing.JTextField jTextdireccion;
    private javax.swing.JTextField jTextnombre;
    private javax.swing.JFormattedTextField jtexttelefono;
    // End of variables declaration//GEN-END:variables
}
